[metrics]
enable = true

[api]
address = ":5006"
public_key = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAHGCyaM2KW5/S31wd+jHuki2QrQw1pyAFUcz888ekiVA=
-----END PUBLIC KEY-----"""

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5432/ge_celo_data"

[chain]
id = 1337
rpc_endpoint = "http://localhost:8545"
